### ISSUE TITLE
How can I use activation of player or add media files in post

### ISSUE THREAD

**Issue by kshutashvili** [TryGhost/Wave#14]
Hello! In your theme I saw media player for audio files but I do not understand how can I add play button on post image ?
For example in your demo https://prnt.sc/1qtqjtp
In my installed theme https://prnt.sc/1qtqnsx
Thanks for theme!

**Comment by minimaluminium** [comment]
Hey there! Make sure you added your audio file URL in `Facebook description`, and uploaded the custom routes file (`routes.yaml`) included in the theme as instructed on the [repo](https://github.com/TryGhost/Wave#adding-episodes).

If not, the theme will make the post a regular blog post, not a podcast episode.

**Comment by kshutashvili** [comment]
Thnx

**Comment by kshutashvili** [comment]
Thnx
