### ISSUE TITLE
where is the place that insert comment

### ISSUE THREAD

**Issue by weidongzhou1994** [TryGhost/Wave#15]
As title, I want to use Disqus, but I don't know the place in the post.hbs

**Comment by minimaluminium** [comment]
Hey @weidongzhou1994, it really depends on where exactly you want to place the comments. For example, if you want to place them after the author list, it should be placed after the closing `</div>` tag of `.author-list` element. The closing tag can be found [here](https://github.com/TryGhost/Wave/blob/cec4198a42eed6049cae243352fe9df81bd5296e/post.hbs#L31).

We ask that you please do not use GitHub for support or feature requests 😄. We use GitHub solely for bug-tracking and on-going feature development.

Our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!
