### ISSUE TITLE
what kinds of audio url are accepted

### ISSUE THREAD

**Issue by msaidf** [TryGhost/Wave#16]
I tried several podcast urls, but they don't work. The only kind of url that works for me is shared link of audio file saved on Dropbox public folder. It would be nice to have clearer documentation about how to use the audio feature of this theme on the repo's README, the demo site, or the theme page on ghost website.

**Comment by minimaluminium** [comment]
Hey @msaidf, the URL should be a direct link to the episode mp3/audio file. It works as instructed in [this](https://ghost.org/docs/tutorials/custom-rss-feed/) tutorial.

More up to date theme instructions are in progress :)
