### ISSUE TITLE
RSS is missing an icon

### ISSUE THREAD

**Issue by marek-lach** [TryGhost/Wave#17]
The RSS link at the bottom of the page is missing an icon, here's a freely licensed, transparent one, that could be used to fix this:

![rss_icon](https://user-images.githubusercontent.com/45913977/148662724-cd43754f-1f6e-47b7-b8de-a6584a848927.png)

**Comment by minimaluminium** [comment]
Hey @marek-lach, would you be able to provide a link to your website? The icon shows up fine on the demo site.

<img width="804" alt="CleanShot 2022-01-10 at 13 18 20@2x" src="https://user-images.githubusercontent.com/1418797/148721222-defec0d3-f9a5-4ec2-8d16-7a08c6ba20f5.png">

**Comment by marek-lach** [comment]
> Hey @marek-lach, would you be able to provide a link to your website? The icon shows up fine on the demo site.
> 
> <img alt="CleanShot 2022-01-10 at 13 18 20@2x" width="804" src="https://user-images.githubusercontent.com/1418797/148721222-defec0d3-f9a5-4ec2-8d16-7a08c6ba20f5.png">

Oh, strangely, just this one icon was blocked by my add blocker, while the others showed fine.
